// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/2/2569 02:50:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/work/inner/sourceCode/inner-academy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/work/inner/sourceCode/inner-academy/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/work/inner/sourceCode/inner-academy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/work/inner/sourceCode/inner-academy/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/work/inner/sourceCode/inner-academy/plugins/**/*.{js,ts,mjs}","E:/work/inner/sourceCode/inner-academy/composables/**/*.{js,ts,mjs}","E:/work/inner/sourceCode/inner-academy/utils/**/*.{js,ts,mjs}","E:/work/inner/sourceCode/inner-academy/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/work/inner/sourceCode/inner-academy/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/work/inner/sourceCode/inner-academy/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/work/inner/sourceCode/inner-academy/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;